name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 17.x ]

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: install modules
        run: npm install

      - name: build prod
        run: npm run build:prod

      - name: lint typescript
        run: npm run lint:ts

      - name: stylelint
        run: npm run lint:scss

      - name: test unit
        run: npm run test:unit

      - name: build storybook
        run: npm run storybook:build

      - name: test ui ci
        run: npm run test:ui:ci
